/****** Object:  Table [dbo].[MParty]    Script Date: 8/29/2022 1:52:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MParty](
	[PartyId] [int] IDENTITY(1,1) NOT NULL,
	[PartyName] [nvarchar](100) NOT NULL,
	[ContentId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_MParty] PRIMARY KEY CLUSTERED 
(
	[PartyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_MParty_PartyName]    Script Date: 8/29/2022 1:52:32 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_MParty_PartyName] ON [dbo].[MParty]
(
	[PartyName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
